FROM atendai/evolution-api:latest

# Porta usada pela Evolution API
ENV SERVER_PORT=8080
ENV PORT=8080

# Desabilitar scripts de database que não existem nesta imagem
ENV DATABASE_ENABLED=false
ENV DATABASE_PROVIDER=sqlite

EXPOSE 8080
